spring:
  datasource:
    url: jdbc:postgresql://192.168.1.214:5432/app?currentSchema=app
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

server:
  error:
    include-stacktrace: never
  servlet:
    context-path: /api

jwt:
  secret: secret
  validity: 3600
  get:
    token:
      uri: /authenticate

logging:
  level:
    com.alvin.jwttokenapp:
      dao: DEBUG
